### ISSUE TITLE
issue with methylratio.py

### ISSUE THREAD

**Issue by lpantano** [zyndagj/BSMAPz#1]
Hi,

I was testing this code, and I got an error saying `flag` variable is not defined at this line: https://github.com/zyndagj/BSMAP/blob/master/methratio.py#L51

It could be that this variable should be `samFLAGS`, the one just before the function?

thanks for having the code here!

**Comment by zyndagj** [comment]
Sorry I just uploaded this change without testing the latest script. I'm going to incorporate some tests and commit my changes later this week. I hope to eventually increase the performance of this script too.

**Comment by lpantano** [comment]
thanks so much!
