### ISSUE TITLE
Differences to original 2.90?

### ISSUE THREAD

**Issue by sklages** [zyndagj/BSMAPz#11]
Where are the differences to original 2.90?

**Comment by zyndagj** [comment]
https://github.com/zyndagj/BSMAPz/releases

The only changes to the BSMAP code itself was to fix compilation errors on OSX. I did rewrite the methylation caller to be multicore and memory efficient, and fixed an old bug with the way the original processed BSP inputs. Lastly, I added a "test" target to the Makefile to ensure results between formats are consistent (which is how I found the bug I mentioned).
