### ISSUE TITLE
SAM2BAM conversion not sucessful

### ISSUE THREAD

**Issue by CS791** [zyndagj/BSMAPz#20]
Hi!

The error pop in while using sam2bam.sh script:
 
"./BSMAPz/sam2bam.sh BSMAP_Output/epiRIL-368_4C_Rep1_L2.sam 
Converting SAM to BAM ...
[W::sam_read1] Parse error at line 11
[main_samview] truncated file.
SAM2BAM conversion not sucessful.
BSMAP_Output/epiRIL-368_4C_Rep1_L2.sam remains unchanged."

Any help is much appriciated

Thank you!
Best Regards

SC

**Comment by zyndagj** [comment]
I updated the `sam2bam.sh` script in version 1.1.2, which should solve your issue.
