### ISSUE TITLE
query regarding methylation level from methylratio output file.

### ISSUE THREAD

**Issue by CS791** [zyndagj/BSMAPz#29]
Hi! Dr. Zynda,

I hope you are doing well. 

This is not regarding any issue, it just a query regarding the BSMAPz output file. The file generated from methylratio.py contains 12 columns. 
I want to plot the methylation level around various genomic features. My question is how I can extract the methylation level from this methylation output file.

I will appreciate it if I get any help regarding this. 

Thank you
Best regards

Saurabh

**Comment by zyndagj** [comment]
Hello!

I don't have a standalone solution, but you may be interested in this pipeline.

https://github.com/zyndagj/ZED-bsmap-align

The ZED pipeline aligns reads, calls methylation, and generates summary tracks for post-processing and visualization. If you don't want to re-run your analysis, you may find it helpful as a starting point for a script of your own.

I will add bedgraph output to my development roadmap though.

Sincerely,
Greg Zynda
