### ISSUE TITLE
Methratio.py does not handle  files

### ISSUE THREAD

**Issue by Akshaygala** [zyndagj/BSMAPz#43]
I am using Python2 (2.7.5) on my UCSF cluster and BSMAPz-1.1.3 as well. I get some other assertion errors - something about repopulation pool, when I use Python3 (3.8.10).
I am getting the following error
[methratio] @Thu May  5 11:40:26 2022   Using 90% of available memory (406157 MB) as limit
[methratio] @Thu May  5 11:40:26 2022   Presorting inputs
methratio.py does not handle  files

Since, it is a cluster, I am using following code to execute:
"""
#!/bin/bash
REF="/wynton/scratch/agala/PASC/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
INgzbam="${!SGE_TASK_ID}"
OUTbase="${INgzbam/.bam/}.txt"
 
. /etc/bashrc
module load CBI
module load Sali
module load samtools/1.9
module load anaconda
export PATH="/wynton/home/pillailab/agala/.local/bin/BSMAPz-1.1.3:$PATH"
export PATH="/wynton/home/pillailab/agala/.local/bin/BSMAPz-1.1.3/samtools:$PATH"

python2 /wynton/home/pillailab/agala/.local/bin/BSMAPz-1.1.3/methratio.py \
-o "${OUTbase}" -d "${REF}" -g -r "${Ingzbam}" 
"""

Can someone please help me with this.

**Comment by zyndagj** [comment]
I have a feeling you're not giving it a file because you first set
```
INgzbam="${!SGE_TASK_ID}"
```
but then use `${Ingzbam}` (with a lowercase n) when running methratio.py. After fixing that, I would make sure that your `SGE_TASK_ID` corresponds to a valid (bam|bsp|sam) file.

**Comment by Akshaygala** [comment]
Yes that indeed was the issue. Thank you. It reads the input file now but however, after running the script again, I get the following error:
"""

[methratio] @Thu May  5 13:26:20 2022   Presorting inputs
[methratio] @Thu May  5 13:26:20 2022   Calling samtools sort on S10.sorted.deduped.bam and using 4716 MB of memory
sort: invalid option -- '@'
sort: invalid option -- 'O'
sort: invalid option -- 'T'
open: No such file or directory
[bam_sort_core] fail to open file 64
open: No such file or directory
[bam_index_build2] fail to open the BAM file.
[methratio] @Thu May  5 13:26:20 2022   Processing 64 chromosomes at a time
[methratio] @Thu May  5 13:26:20 2022   Reading GL000194.1 from S10.sorted.deduped.tmpSrt.bam with samtools
[methratio] @Thu May  5 13:26:20 2022   S10.sorted.deduped.tmpSrt.bam should have been presorted.

there is more and it just ends with "1 failed to process"
"""
I had already sorted and deduplicated bam files before processing the methratio.py.
I have activated both - 1) module for samtools in my cluster 2) given the PATH to samtools which came with BSMAPz installation.

**Comment by zyndagj** [comment]
I have a feeling it's because you're adding an old version of samtools to your path. Try commenting out

```
export PATH="/wynton/home/pillailab/agala/.local/bin/BSMAPz-1.1.3/samtools:$PATH"
```

so you can use samtools from the `samtools/1.9` module and re-running.

**Comment by Akshaygala** [comment]
Yes that was indeed the issue. Thank you for resolving it.
