### ISSUE TITLE
methratio.py: samtools view: invalid option -- 'X'

### ISSUE THREAD

**Issue by SarkaS** [zyndagj/BSMAPz#7]
Hi,
a new issue came up to me when I was trying to lounch methratio.py function which worked perfectly about a month ago.

My code for samtools v.1.9 and bsmap v.2.90:
`(bioinfo) root@cloud61b:/home/Illumina# methratio.py -d /Reference/hg19.fa -m 1 -z -i skip -o SAMPLE.methylation_results.txt SAMPLE.bam`
`[methratio] @Tue Dec 11 10:17:21 2018   loading reference file: /Reference/hg19.fa ...`
`samtools view: invalid option -- 'X'`

At first I thought there has been a change in new version of samtools but I tried downgraded to 1.8 and 1.7 and the error is still `view: invalid option -- 'X'`.

Do you have any idea what's wrong and what shloud I do to fix this? 

Thanks!
Sarka

**Comment by zyndagj** [comment]
Hi Sarka,

I think you have the version from the "original" branch. Let me finish up merging my changes from development to master and then you can grab a fresh copy of BSMAPz, which will enforce memory and cpu limits.

Thanks!
Greg Zynda

**Comment by SarkaS** [comment]
Thanks for your answer Greg! 
I appreciate your hard work on the software! And when can I expect your new updated version and also I use minicoda2 to install my programs, will it be available there too?

Best,
Sarka

**Comment by zyndagj** [comment]
Sorry for the long delay over the holidays. The latest release I just published should work.

https://github.com/zyndagj/BSMAPz/releases/tag/1.1.0

Let me know if you have any issues or feedback!

**Comment by zyndagj** [comment]
BSMAPz is now available through conda

https://anaconda.org/zyndagj/bsmapz
